services:
  app:
    build:
      context: .
      args:
        - DEV=true
    container_name: todo-app-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5

volumes:
  dev-db-data:
